# Codemagic CI/CD Configuration
# Documentation: https://docs.codemagic.io/yaml-basic-configuration/yaml-getting-started/

workflows:
  android-split-apk:
    name: Android Build (Split APKs)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
      java: 17
      groups:
        # You should create an environment group in Codemagic UI 
        # and add your EXPO_PUBLIC_* variables there.
        - project_env 
      vars:
        # Static variables can go here
        PACKAGE_NAME: "com.ssabee1722.onspaceapp"

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Expo Prebuild
        script: |
          # Generates the native android folder
          npx expo prebuild --platform android --no-install

      - name: Enable ABI Splitting (arm64-v8a, etc.)
        script: |
          # This script modifies the generated android/app/build.gradle 
          # to enable separate APKs for different CPU architectures.
          # This will generate specific APKs for arm64-v8a, armeabi-v7a, etc.
          
          GRADLE_FILE="android/app/build.gradle"
          if [ -f "$GRADLE_FILE" ]; then
            # Enable separate builds per architecture
            sed -i '' 's/def enableSeparateBuildPerCPUArchitecture = false/def enableSeparateBuildPerCPUArchitecture = true/' "$GRADLE_FILE"
            echo "Successfully enabled ABI splitting in build.gradle"
          else
            echo "Error: android/app/build.gradle not found. Prebuild might have failed."
            exit 1
          fi

      - name: Set Android SDK Location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

      - name: Build Android Release APK
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      # This will capture all generated APKs, including the split ones
      # Look for filenames like app-arm64-v8a-release.apk
      - android/app/build/outputs/apk/release/*.apk

    publishing:
      # Optional: setup email notifications
      email:
        recipients:
          - your-email@example.com # Replace with your email
        notify:
          success: true
          failure: true
