# Codemagic CI/CD Configuration
# Documentation: https://docs.codemagic.io/yaml-basic-configuration/yaml-getting-started/

workflows:
  android-split-apk:
    name: Android Build (Split APKs)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: latest
      java: 17
      groups:
        - VAR 
      vars:
        PACKAGE_NAME: "com.ssabee1722.onspaceapp"

    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Expo Prebuild
        script: |
          # Generates the native android folder
          npx expo prebuild --platform android --no-install

      - name: Configure Splitting and Minification
        script: |
          # 1. Enable ABI Splitting in build.gradle
          # We insert the splits block into the android definition
          GRADLE_FILE="android/app/build.gradle"
          if [ -f "$GRADLE_FILE" ]; then
            # Use sed to insert the splits block after the namespace line
            # This will generate separate APKs for each architecture
            sed -i '' '/namespace/a\
    splits {\
        abi {\
            reset()\
            enable true\
            universalApk false\
            include "armeabi-v7a", "arm64-v8a", "x86", "x86_64"\
        }\
    }' "$GRADLE_FILE"
            echo "Splits configuration added to build.gradle"
          fi

          # 2. Enable ProGuard/R8 for massive size reduction (from 200MB+ to ~20MB)
          PROPS_FILE="android/gradle.properties"
          echo "android.enableProguardInReleaseBuilds=true" >> "$PROPS_FILE"
          echo "android.enableShrinkResourcesInReleaseBuilds=true" >> "$PROPS_FILE"
          echo "Minification enabled in gradle.properties"

      - name: Set Android SDK Location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties

      - name: Build Android Release APK
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      # This will now capture multiple APKs:
      # - app-arm64-v8a-release.apk
      # - app-armeabi-v7a-release.apk
      # etc.
      - android/app/build/outputs/apk/release/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
