/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/class-management`; params?: Router.UnknownInputParams; } | { pathname: `/confirm-success`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/qr-scanner`; params?: Router.UnknownInputParams; } | { pathname: `/role-select`; params?: Router.UnknownInputParams; } | { pathname: `/staff-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/staff-login`; params?: Router.UnknownInputParams; } | { pathname: `/staff-signup`; params?: Router.UnknownInputParams; } | { pathname: `/student-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/student-login`; params?: Router.UnknownInputParams; } | { pathname: `/student-signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/class-management`; params?: Router.UnknownOutputParams; } | { pathname: `/confirm-success`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/qr-scanner`; params?: Router.UnknownOutputParams; } | { pathname: `/role-select`; params?: Router.UnknownOutputParams; } | { pathname: `/staff-dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/staff-login`; params?: Router.UnknownOutputParams; } | { pathname: `/staff-signup`; params?: Router.UnknownOutputParams; } | { pathname: `/student-dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/student-login`; params?: Router.UnknownOutputParams; } | { pathname: `/student-signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/class-management${`?${string}` | `#${string}` | ''}` | `/confirm-success${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/qr-scanner${`?${string}` | `#${string}` | ''}` | `/role-select${`?${string}` | `#${string}` | ''}` | `/staff-dashboard${`?${string}` | `#${string}` | ''}` | `/staff-login${`?${string}` | `#${string}` | ''}` | `/staff-signup${`?${string}` | `#${string}` | ''}` | `/student-dashboard${`?${string}` | `#${string}` | ''}` | `/student-login${`?${string}` | `#${string}` | ''}` | `/student-signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/class-management`; params?: Router.UnknownInputParams; } | { pathname: `/confirm-success`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/qr-scanner`; params?: Router.UnknownInputParams; } | { pathname: `/role-select`; params?: Router.UnknownInputParams; } | { pathname: `/staff-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/staff-login`; params?: Router.UnknownInputParams; } | { pathname: `/staff-signup`; params?: Router.UnknownInputParams; } | { pathname: `/student-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/student-login`; params?: Router.UnknownInputParams; } | { pathname: `/student-signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
